Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path("convert/", include("guest_user.urls")),
    
    path('', include('core.urls')),
    path('carro/', include('carro.urls'), name='carro'),
    path('gestionPedidos/', include('gestionPedidos.urls')),
    path('ordenes/', include('ordenes.urls')),
    path('cupones/', include('cupones.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path
from .import views

app_name = "carro"

urlpatterns = [
    path('detalle_carro/', views.detalle_carro, name='detalle_carro'),
    path('anadir/<id_producto>/', views.carro_mas, name='carro_mas'),
    path('restar/<id_producto>/', views.carro_menos, name='carro_menos'),
    path('limpiar/', views.carro_limpiar, name='carro_limpiar')
]

core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('registrar/', registrar, name='registrar'),
    path('categoria/<str:foo>/', categoria, name='categoria'),
    path('ver-orden/', busca_ordenes, name='busca-ordenes'),
    path('contacto/', contacto, name='contacto'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', exit, name='logout'),
    path('productos/<str:id_producto>', detalle_producto, name='detalle_producto')
]

ordenes/urls.py
from django.urls import path
from .views import *

app_name='ordenes'

urlpatterns = [
    path('checkout/', orden_nuevo, name="orden_nuevo"),
    path('ordenes/', ordenes, name='ordenes'),
    path('orden/<int:pk>/', orden_detalle, name="orden_detalle"),
    path('admin/ordenlist/', ordenes_lista, name="ordenes_lista"),
    path('admin/estado/<int:id>', orden_estado, name="orden_estado"),  
    path('admin/editar/<int:id>', orden_editar, name='orden_editar'),
    path('admin/borrar/<int:id>', orden_borrar, name='orden_borrar'),
    
    path('api/v1/transbank/transaction/create/', webpay_create, name='webpay-create'),
    path('exito/', webpay_retorno, name='webpay-retorno')
]

carro/models.py
from django.db import models

# Create your models here.

carro/forms.py
from django import forms

cantidades_producto = [(i, str(i)) for i in range (1, 21)]

class anadirProductoForm(forms.Form):
    cantidad = forms.TypedChoiceField(choices=cantidades_producto, coerce=int)
    update = forms.BooleanField(required=False, initial= False, widget=forms.HiddenInput)

carro/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.views.decorators.http import require_POST
from gestionPedidos.models import Producto
from .carro import Carro
from .forms import anadirProductoForm
from cupones.forms import CuponForm

@require_POST
def carro_mas(request, id_producto):
    carro = Carro(request)
    producto = Producto.objects.get(id_producto=id_producto)
    form = anadirProductoForm(request.POST)
    if form.is_valid():
        carro.anadir(
            producto=producto,
            cantidad=form.cleaned_data['cantidad'],
            update=form.cleaned_data['update'])
    return redirect('carro:detalle_carro')


    
def carro_menos(request, id_producto):
    carro = Carro(request)
    producto = Producto.objects.get(id_producto=id_producto)
    carro.eliminar(producto=producto)
    return redirect('carro:detalle_carro')

def carro_eliminar(request, id_producto):
    carro = Carro(request)
    producto = Producto.objects.get(id_producto=id_producto)
    carro.eliminar(producto=producto)
    return redirect('carro:detalle_carro')

def carro_limpiar(request):
    carro = Carro(request)
    carro.limpiar()
    return redirect('/')

def detalle_carro(request):
    carro = Carro(request)
    for item in carro:
        item['update_cantidad_form'] = anadirProductoForm(initial={'cantidad': item['cantidad'], 'update': True})
    return render(request, 'detalle_carro.html', {'carro': carro})

carro/templates/detalle_carro.html
{% extends 'base.html' %}
{% load guest_user %}
{% load static %}

{% block title %}
  Mi carrito de compras!
{% endblock %}

{% block first_content %}

{% endblock %}
{% block second_content %}
  {% if request.session.carro.items %}
    <div class="carrito-container">
      <div class="carrito-titulo">
        <h1>Carrito de compras</h1>
      </div>
      <div class="carrito-productos">
        <table class="table">
          <thead>
            <th>Pedido</th>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Precio</th>
            <th>Total</th>
          </thead>
          <tbody>
            {% load bootstrap_icons %}
            {% load humanize %}

            {% for item in carro %}
              {% with producto=item.producto %}
                <tr>
                  <td>
                    <a href="{{ producto.get_absolute_url }}">
                      <img src="{% if producto.imagen %}
                          {{ producto.imagen.url }}
                        {% else %}
                          {% static 'img/default.jpg' %}
                        {% endif %}"
                        alt="..."
                        style="height: 130px; width: auto" />
                    </a>
                  </td>
                  <td>{{ producto.nombre }}</td>
                  <td>
                    <form class="carrito-form" action="{% url 'carro:carro_mas' producto.id_producto %}" method="post">
                      {% csrf_token %}
                      {{ item.update_cantidad_form.cantidad }}
                      {{ item.update_cantidad_form.update }}
                      <input type="submit" value="Actualizar" class="carrito-actualizar" />
                    </form>
                    <button class="carrito-quitar"><a href="{% url 'carro:carro_menos' producto.id_producto %}">Quitar</a></button>
                  </td>
                  <td class="carrito-precio">$ {{ item.precio|intcomma }}</td>
                  <td class="carrito-total">$ {{ item.precio_total|intcomma }}</td>
                </tr>
              {% endwith %}
            {% endfor %}
          </tbody>
        </table>
      </div>

      <div class="carrito-resumen">
        <h2 class="h2-resumen">Resumen</h2>
        <div class="resumen-cantidad">Cantidad Total</div>
        <div class="resumen-local">
          <div class="resumen-title">Local de retiro</div>
          <select class="resumen-select" name="" id="">
            <option value="volvo">Sucursal La Florida</option>
            <option value="saab">Sucursal Puente Alto</option>
          </select>
        </div>

        <div class="resumen-total">Total: $ {{ carro.carro_total|intcomma }}</div>
        <a class="resumen-checkout" href="{% url 'ordenes:orden_nuevo' %}"><button>Checkout</button></a>
      </div>
    </div>
  {% else %}
    <div class="detalle-titulo">
      <h3>¡Tu carrito de compras está vacío!</h3>
      <img src="{% static 'img/flork-sad.png' %}" alt="" />
    </div>
  {% endif %}
{% endblock %}