Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path("convert/", include("guest_user.urls")),
    
    path('', include('core.urls')),
    path('carro/', include('carro.urls'), name='carro'),
    path('gestionPedidos/', include('gestionPedidos.urls')),
    path('ordenes/', include('ordenes.urls')),
    path('cupones/', include('cupones.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('registrar/', registrar, name='registrar'),
    path('categoria/<str:foo>/', categoria, name='categoria'),
    path('ver-orden/', busca_ordenes, name='busca-ordenes'),
    path('contacto/', contacto, name='contacto'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', exit, name='logout'),
    path('productos/<str:id_producto>', detalle_producto, name='detalle_producto')
]

cupones/urls.py
from django.urls import path
from .views import *

app_name='cupones'

urlpatterns = [
    path('aplicar/', aplicar_cupon, name='aplicar')
]

ordenes/urls.py
from django.urls import path
from .views import *

app_name='ordenes'

urlpatterns = [
    path('checkout/', orden_nuevo, name="orden_nuevo"),
    path('ordenes/', ordenes, name='ordenes'),
    path('orden/<int:pk>/', orden_detalle, name="orden_detalle"),
    path('admin/ordenlist/', ordenes_lista, name="ordenes_lista"),
    path('admin/estado/<int:id>', orden_estado, name="orden_estado"),  
    path('admin/editar/<int:id>', orden_editar, name='orden_editar'),
    path('admin/borrar/<int:id>', orden_borrar, name='orden_borrar'),
    
    path('api/v1/transbank/transaction/create/', webpay_create, name='webpay-create'),
    path('exito/', webpay_retorno, name='webpay-retorno')
]

ordenes/models.py
from django.db import models
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from gestionPedidos.models import Producto
from cupones.models import Cupon
from django.contrib.auth import get_user_model

User = get_user_model()

class Orden (models.Model):
    class Estado (models.TextChoices):
        PENDIENTE = "PENDIENTE"
        EN_PREPARACION = "EN PREPARACIÓN"
        COMPLETADA = "COMPLETADA"
        CANCELADA = "CANCELADA"
    
    nombre = models.CharField(max_length=30, verbose_name="nombre")
    apellido = models.CharField(max_length=50, verbose_name="apellido")
    direccion = models.CharField(max_length=200, verbose_name="direccion")
    comuna = models.CharField(max_length=50, verbose_name="comuna")
    ciudad = models.CharField(max_length=50, verbose_name="ciudad")
    telefono = models.CharField(max_length=12, verbose_name="telefono", default=0)
    comentario = models.CharField(max_length=500, verbose_name="comentario", blank=True)
    cupon = models.ForeignKey(Cupon, verbose_name="cupon", on_delete=models.CASCADE, blank=True, null=True, default=False)
    subtotal = models.IntegerField(verbose_name="subtotal")
    descuento = models.IntegerField(verbose_name="descuento", default=0, blank=True)
    total_oc = models.IntegerField(verbose_name="total_oc", default=0)
    creada = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=20, choices=Estado.choices, default=Estado.PENDIENTE)
    user = models.ForeignKey(User, verbose_name="user", on_delete=models.CASCADE)
    
    class Meta:
        verbose_name= "Orden"
        verbose_name_plural = "Ordenes"
        get_latest_by = "id"
        
    def __str__(self):
        return 'Orden #{}'.format(self.id)
    
    def valor_total(self):
        valor_total = self.sub_total() - self.descuento()
        return valor_total
        
    def total(self):
        subtotal = sum(item.total_item() for item in self.items.all())
        total = subtotal - subtotal*(self.descuento / Decimal('100'))
        return total
    
class OrdenItem (models.Model):
    orden = models.ForeignKey(Orden, verbose_name="orden", on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, verbose_name="orden_productos", on_delete=models.CASCADE)
    precio = models.IntegerField(verbose_name="precio")
    cantidad = models.IntegerField(verbose_name="cantidad")
    
    def __str__(self):
        return 'Orden #{}'.format(self.orden.id)
    
    def total_item(self):
        total_item = self.precio * self.cantidad
        return total_item
    
class Transaccion (models.Model):
    orden = models.ForeignKey(Orden, verbose_name="orden", on_delete=models.CASCADE)
    vci = models.CharField(max_length=5, verbose_name="VCI")
    status = models.CharField(max_length=65, verbose_name="status")
    buy_order = models.CharField(max_length=27, verbose_name="num_trans")
    session_id = models.CharField(max_length=62, verbose_name="id_session")
    card_number = models.CharField(verbose_name="num_tarjeta")
    accounting_date = models.CharField(max_length=4, verbose_name="fecha_auth")
    transaction_date = models.CharField(verbose_name="fecha_trans", null=True)
    authorization_code = models.CharField(max_length=7, verbose_name="cod_auth")
    payment_type_code = models.CharField(max_length=3, verbose_name="tipo_pago")
    response_code = models.CharField(max_length=3, verbose_name="cod_respuesta")
    installments_number = models.CharField(max_length=3, verbose_name="num_cuotas")
    
    class Meta:
        verbose_name= "Transacción"
        verbose_name_plural = "Transacciones"
        
    def __str__(self):
        return (self.accounting_date)

    

    
    

ordenes/forms.py
from django import forms
from .models import Orden

class OrdenForm (forms.ModelForm):
    class Meta:
        model = Orden
        fields = [
            'nombre',
            'apellido',
            'direccion',
            'telefono',
            'comuna',
            'ciudad',
            'comentario',
            
        ]
        labels = {
            'nombre': 'Nombre',
            'apellido' : 'Apellido',
            'direccion' : 'Direccion',
            'telefono' : 'Telefono',
            'comuna' : 'Comuna',
            'ciudad' : 'Ciudad',
            'comentario' : 'Comentario',
            'cupon' : 'cupon',
            'descuento' : 'descuento',
            'total_oc' : 'total_oc',
            'user' : 'user'
        }
        widgets = {
            'nombre' : forms.TextInput(attrs={'class' : 'form-control'}),
            'apellido' : forms.TextInput(attrs={'class' : 'form-control'}),
            'direccion' : forms.TextInput(attrs={'class' : 'form-control'}),
            'telefono' : forms.TextInput(attrs={'class' : 'form-control'}),
            'comuna' : forms.TextInput(attrs={'class' : 'form-control'}),
            'ciudad' : forms.TextInput(attrs={'class' : 'form-control'}),
            'comentario' : forms.TextInput(attrs={'class' : 'form-control'}),
            'cupon' : forms.TextInput(attrs={'is_hidden' : True}),
            'descuento' : forms.TextInput(attrs={'is_hidden' : True}),
            'total_oc' : forms.TextInput(attrs={'is_hidden' : True}),
            'user' : forms.TextInput(attrs={'is_hidden' : True})
        }
        
class OrdenFormAdmin(forms.ModelForm):
    class Meta:
        model = Orden
        fields = ['estado']
        labels = {'estado' : 'update'}
        widgets = {forms.Select(attrs={'class' : 'form-control'})}
        

ordenes/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import UpdateView
from django.utils.decorators import method_decorator
from django.http import HttpResponse, HttpResponseBadRequest
from django.db import transaction
from guest_user.decorators import allow_guest_user
from .forms import OrdenForm, OrdenFormAdmin
from cupones.models import Cupon
from cupones.forms import CuponForm
from .models import Orden, OrdenItem, Transaccion
from gestionPedidos.models import Producto
from carro.carro import Carro
import requests
import random
import json
import datetime

User = get_user_model()

@allow_guest_user
def orden_nuevo(request):
    carro = Carro(request)
    usuario = User.objects.get(username=request.user.username)
    subtotal = carro.carro_total()
    total = carro.total()
    if carro.cupon:
        cupon = carro.cupon
        descuento = carro.descuento()
        desc = Cupon.desc(cupon)
        print("desc:", desc)
    else:
        cupon = None
        descuento = 0
        
    if request.method == 'POST':
        try:
            transaction.set_autocommit(False)
            form = OrdenForm(request.POST)
            if form.is_valid():
                nombre = form.cleaned_data.get('nombre')
                apellido = form.cleaned_data.get('apellido')
                direccion = form.cleaned_data.get('direccion')
                comuna = form.cleaned_data.get('comuna')
                ciudad = form.cleaned_data.get('ciudad')
                telefono = form.cleaned_data.get('telefono')
                comentario = form.cleaned_data.get('comentario')
                subtotal = subtotal
                cupon = cupon
                descuento = descuento
                total_oc = total
                user = usuario
                orden = Orden.objects.create(
                    nombre = nombre,
                    apellido = apellido,
                    direccion = direccion,
                    comuna = comuna,
                    ciudad = ciudad,
                    telefono = telefono,
                    comentario = comentario,
                    subtotal = subtotal,
                    cupon = cupon,
                    descuento = descuento,
                    total_oc = total_oc,
                    user = user
                )      
                orden.save()      
              
                for item in carro:
                    OrdenItem.objects.create(
                        orden = orden,
                        producto = item['producto'],
                        precio = item['precio'],
                        cantidad = item['cantidad']
                    )
                carro.limpiar()
                
                transaction.commit()                
                return render(request, 'crear.html', {'orden' : orden})
        except:
            transaction.rollback()
            return redirect("/")
        finally:
            transaction.set_autocommit(True)
    else:
        form = OrdenForm()
        cuponform = CuponForm()
        context = {'carro' : carro, 'form' : form, 'cuponform' : CuponForm}
        return render(request, 'checkout.html', context)
    
def header_request_transbank():
    headers = {
        "Authorization": "Token",
        "Tbk-Api-Key-Id": "597055555532",
        "Tbk-Api-Key-Secret": "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C",
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": "*",
        'Referrer-Policy': 'origin-when-cross-origin',
    }
    return headers

def webpay_create(request):
    carro = Carro(request)
    usuario = User.objects.get(username=request.user.username)
    subtotal = carro.carro_total()
    if carro.cupon:
        cupon = carro.cupon
        descuento = carro.descuento()
        desc = Cupon.desc(cupon)
        print("desc:", desc)
    else:
        cupon = None
        descuento = 0
    # Calcula el valor total sumando los subtotales de los productos en el carrito
    total = int(carro.total())

    if request.method == 'POST':
        form = OrdenForm(request.POST)
        if form.is_valid():
            nombre = form.cleaned_data.get('nombre')
            apellido = form.cleaned_data.get('apellido')
            direccion = form.cleaned_data.get('direccion')
            comuna = form.cleaned_data.get('comuna')
            ciudad = form.cleaned_data.get('ciudad')
            telefono = form.cleaned_data.get('telefono')
            comentario = form.cleaned_data.get('comentario')
            subtotal = subtotal
            cupon = cupon
            descuento = descuento
            total_oc = total
            user = usuario
            orden = Orden.objects.create(
                nombre = nombre,
                apellido = apellido,
                direccion = direccion,
                comuna = comuna,
                ciudad = ciudad,
                telefono = telefono,
                comentario = comentario,
                subtotal = subtotal,
                cupon = cupon,
                descuento = descuento,
                total_oc = total_oc,
                user = user
            )      
            orden.save()      
              
            for item in carro:
                OrdenItem.objects.create(
                    orden = orden,
                    producto = item['producto'],
                    precio = item['precio'],
                    cantidad = item['cantidad']
                )
            carro.limpiar()               
            
            #return render(request, 'crear.html', {'orden' : orden})
        
        data = {
            "buy_order": str(random.randrange(1000000, 99999999)),
            "session_id": str(random.randrange(1000000, 99999999)),
            "amount": total,
            "return_url": "http://127.0.0.1:8000/ordenes/exito",
        }
        url = "https://webpay3gint.transbank.cl/rswebpaytransaction/api/webpay/v1.2/transactions"
        headers = header_request_transbank()
        respuesta = requests.post(url, json=data, headers=headers)

        if respuesta.status_code == 200:
            response = respuesta.json()
            newurl = response.get('url')
            tokenrs = response.get('token')
            print("json: ")
            print(response)
            print("url: ")
            print(newurl)
            print("token: ")
            print(tokenrs)
            return render(request, 'crear.html', {
                'url': newurl, 
                'token': tokenrs, 
                'total': total, 
                'respuesta' : respuesta})
        else:
            return HttpResponse('Error al enviar la solicitud al servidor de Transbank')

    return HttpResponseBadRequest('Método no permitido')

def webpay_retorno(request):
    orden = Orden.objects.latest()
    token = request.GET.get('token_ws')
    data = {'token' : token}
    url = "https://webpay3gint.transbank.cl/rswebpaytransaction/api/webpay/v1.2/transactions/"+token
    headers = header_request_transbank()
    respuesta = requests.put(url, json=data, headers=headers)    
    if respuesta.status_code == 200:
        response = respuesta.json()
        vci = response.get('vci')
        status = response.get('status')
        print(status)
        buy_order = response.get('buy_order')
        session_id = response.get('session_id')
        card_detail = response.get('card_detail')
        card_number = json.dumps([card_detail][0]['card_number']).replace('"', '')
        accounting_date = response.get('accounting_date')
        transaction_date = response.get('transaction_date')
        fecha = datetime.datetime.fromisoformat(transaction_date)
        print(fecha)
        authorization_code = response.get('authorization_code')
        payment_type_code = response.get('payment_type_code')
        response_code = response.get('response_code')
        installments_number = response.get('installments_number')
        orden = orden
        if status == "AUTHORIZED":
            transaccion = Transaccion.objects.create(
                vci = vci,
                status = status,
                buy_order = buy_order,
                session_id= session_id,
                card_number = card_number,
                accounting_date = accounting_date,
                transaction_date = transaction_date,
                authorization_code = authorization_code,
                payment_type_code = payment_type_code,
                response_code = response_code,
                installments_number = installments_number,
                orden = orden
            )
            return render(request, 'exito.html', {'orden' : orden, 'fecha':fecha, 'respuesta' : respuesta, 'transaccion' : transaccion})
        else:
            return render(request, 'rechazado.html')
            

@staff_member_required
def ordenes_lista(request):
    form = OrdenFormAdmin()
    if request.method == 'POST':
        form = OrdenFormAdmin(request.POST)
        if form.is_valid():
            estado = form.cleaned_data.get('estado')
            Orden.objects.update(estado=estado)
        else:
            form = OrdenFormAdmin
            
    context = {'ordenes' : Orden.objects.all(), 'form' : form}
    return render(request,'admin/ordenlist.html',context)  
        

@staff_member_required
def orden_editar(request, id):
    try:
        orden = Orden.objects.get(id = id)
        ordenForm = OrdenForm(instance = orden)
        items = OrdenItem.objects.filter(orden=id)
        if request.method == 'POST':
            ordenForm = OrdenForm(request.POST, instance = orden)
            if ordenForm.is_valid():
                ordenForm.save()
                return redirect(reverse('ordenes:ordenes_lista') + '?UPDATED')
            else:

ordenes/templates/checkout.html
{% extends 'base.html' %}
{% load guest_user %}
{% load static %}

{% block title %}
  Checkout
{% endblock %}

{% block first_content %}
{% if 'OK' in request.GET %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    Cupón <strong>ingresado</strong> satisfactoriamente.
    Tienes un descuento de {{carro.cupon.desc}}%.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endif %}

{% if 'NO_EXISTS' in request.GET %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Cupón no válido.</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endif %}

{% endblock %}

{% block second_content %}
  <div class="container-checkout">
    <div class="checkout-datos">
      <div class="checkout-title">
        <h2>Checkout</h2>
      </div>
      <form class="checkout-form" method="post" action="{% url 'ordenes:webpay-create' %}">
        {% csrf_token %}
        {{ form }}
        <div class="checkout-ordenar-button">
          <input type="submit" value="Ordenar" />
        </div>
      </form>
    </div>
    <div class="checkout-resumen">
      <div class="checkout-resumen-title">
        <h6>Tu pedido</h6>
      </div>
      <ul class="checkout-list">
        {% load humanize %}
        {% for item in carro %}
          <li>
            - {{ item.producto.nombre }} x {{ item.cantidad }} <br>
            <span>----- $ {{ item.precio|intcomma }}</span>
          </li>
        {% endfor %}
      </ul>

      {% if user|is_guest_user %}
        <div class="resumen-invitacion">
          <p>Únete para guardar tus compras y ganar premios</p>
          <div class="carrito-signup">
            <a href="{% url 'registrar' %}"><button class="checkout-unirme">Unirme</button></a>
          </div>
        </div>
      {% else %}
        <div class="checkout-cupon">
          <p>Usa tu cupón:</p>
          <form action="{% url 'cupones:aplicar' %}" method="post">
            {% csrf_token %}
            {{ cuponform }}
            {% if cuponform.is_valid %}
              <button onclick="cuponAlert()" class="btn btn-success" id="cupon-form" type="submit">Aplicar</button>
            {% else %}
              <button href="#" class="btn btn-success cupon-button" type="submit">Aplicar</button>
            {% endif %}
          </form>
        </div>
      {% endif %}

      <div class="checkout-subtotal">
        <div class="subtotal">
          <li>Subtotal: $ {{ carro.carro_total|linebreaksbr|intcomma }}</li>
          <li>Descuento: $ {{ carro.descuento|linebreaksbr|intcomma }}</li>
          <br />
          <li>
            <strong>Total: $ {{ carro.total|intcomma }}</strong>
          </li>
        </div>
      </div>
    </div>
  </div>

  <script>
    $('#cupon-form').on('submit', function(event){
      event.preventDefault();
      console.log("form submitted!")
  });

    function cuponAlert() {
      /*if(estado){
        //sweet
      }else{
        //error
      }*/
      Swal.fire({
        title: '¡Cupón aplicado!',
        text: 'Tienes un descuento de {{carro.cupon.desc}}%.',
        icon: 'success',
        timer: 2000,
        confirmButtonText: 'OK'
      })
    }
  </script>
{% endblock %}

ordenes/templates/crear.html
{% load static %}

<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Procesando pago...</title>
</head>
<body onload="document.forms['transbank_form'].submit()">
    <form id="transbank_form" action="{{ url }}" method="post">
        <input type="hidden" name="token_ws" value="{{ token }}">
        <input type="hidden" name="amount" value="{{ total }}">
    </form>
</body>
</html>

ordenes/templates/exito.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Gracias por tu compra.
{% endblock %}
{% block content %}
  <div class="container-exito">
    <div class="row-exito">
      <div class="col-md-8 col-md-offset-2">
        <h3 class="page-header">Gracias por tu compra.</h3>
        <p>
          Tu compra se ha realizado satisfactoriamente. El número de tu orden es <strong>{{ orden.id }}</strong>.
        </p>
        <div class="exito-flork">
          <img class="" src="{% static 'img/flork-love.gif' %}" />
        </div>
        {% load humanize %}
        <div class="detalle-transaccion">
          <div class="detalle-header">
            <h5>Detalle de transacción</h5>
          </div>
          <table class="table table-bordered table-transaccion">
            <tbody>
              <tr>
                <th class="detalle-info" scope="row">Fecha:</th>
                <td>{{ fecha }}</td>
              </tr>
              <tr>
                <th class="detalle-info" scope="row">Número de transacción:</th>
                <td>{{ transaccion.buy_order }}</td>
              </tr>
              <tr>
                <th class="detalle-info" scope="row">Número de tarjeta:</th>
                <td>{{ transaccion.card_number }}</td>
              </tr>
              <tr>
                <th class="detalle-info" scope="row">Cod. de autorización:</th>
                <td>{{ transaccion.authorization_code }}</td>
              </tr>
              <tr>
                <th class="detalle-info" scope="row">Total cancelado:</th>
                <td>$ {{ orden.total_oc|intcomma }}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="detalle-aprobado">
          <img src="{% static 'img/check-symbol.svg' %}" alt="" />
          <p>Pago Aprobado</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ordenes/templates/rechazado.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Error.
{% endblock %}
{% block content %}
  <div class="container-exito">
    <div class="row-exito">
      <div class="col-md-8 col-md-offset-2">
        <h3 class="page-header">Pago rechazado.</h3>
        <p>
          Ha ocurrido un error en la transacción. Por favor, intentalo nuevamente.
        </p>
        <div class="exito-flork">
          <img class="" src="{% static 'img/flork-sad2.png' %}" />
        </div>
{% endblock %}