Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path("convert/", include("guest_user.urls")),
    
    path('', include('core.urls')),
    path('carro/', include('carro.urls'), name='carro'),
    path('gestionPedidos/', include('gestionPedidos.urls')),
    path('ordenes/', include('ordenes.urls')),
    path('cupones/', include('cupones.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path
from .import views

app_name = "carro"

urlpatterns = [
    path('detalle_carro/', views.detalle_carro, name='detalle_carro'),
    path('anadir/<id_producto>/', views.carro_mas, name='carro_mas'),
    path('restar/<id_producto>/', views.carro_menos, name='carro_menos'),
    path('limpiar/', views.carro_limpiar, name='carro_limpiar')
]

core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('registrar/', registrar, name='registrar'),
    path('categoria/<str:foo>/', categoria, name='categoria'),
    path('ver-orden/', busca_ordenes, name='busca-ordenes'),
    path('contacto/', contacto, name='contacto'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', exit, name='logout'),
    path('productos/<str:id_producto>', detalle_producto, name='detalle_producto')
]

ordenes/urls.py
from django.urls import path
from .views import *

app_name='ordenes'

urlpatterns = [
    path('checkout/', orden_nuevo, name="orden_nuevo"),
    path('ordenes/', ordenes, name='ordenes'),
    path('orden/<int:pk>/', orden_detalle, name="orden_detalle"),
    path('admin/ordenlist/', ordenes_lista, name="ordenes_lista"),
    path('admin/estado/<int:id>', orden_estado, name="orden_estado"),  
    path('admin/editar/<int:id>', orden_editar, name='orden_editar'),
    path('admin/borrar/<int:id>', orden_borrar, name='orden_borrar'),
    
    path('api/v1/transbank/transaction/create/', webpay_create, name='webpay-create'),
    path('exito/', webpay_retorno, name='webpay-retorno')
]

core/models.py
from django.db import models
import re
from django.contrib.auth import get_user_model

User = get_user_model()
class UserManager(models.Manager):
    def validador(self, postData):
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        SOLO_LETRAS = re.compile(r'^[a-zA-Z.]+$')
        PASSWORD_REGEX = re.compile(r'^(?=\w*\d)(?=\w*[A-Z])(?=\w*[a-z])\S{8,16}$')
    
        errors = {}
    
        if len(Cliente.objects.filter(correo=postData['correo'])) > 0:
           errors['correo_exits'] = "Correo ya existente."
    
        else:
            if len(postData['nombre'].strip()) < 2 or len(postData['nombre'].strip()) > 40:
                errors['nombre_len'] = "Nombre debe tener entre 2 y 40 caracteres"
            if len(postData['apellido'].strip()) < 2 or len(postData['apellido'].strip()) > 40:
                 errors['apellido_len'] = "Apellido debe tener entre 2 y 40 caracteres"
            
        if not SOLO_LETRAS.match(postData['nombre']) or not SOLO_LETRAS.match(postData['apellido']):
            errors['solo_letras']  = "Favor ingresar solo letras."
        
        if not EMAIL_REGEX.match(postData['correo']):
            errors['correo'] = "Correo no válido."
            
        if not PASSWORD_REGEX.match(postData['password']):
            errors['password_format'] = "Formato de contraseña no válido"
            
        if postData['password'] != postData['password_confirm']:
            errors['password_confirm'] = "Contraseñas no coinciden"

        return errors
class Contacto(models.Model):
    nombre=models.CharField(max_length=30, verbose_name="nombre")
    apellido=models.CharField(max_length=30, verbose_name="apellido")
    correo=models.EmailField(verbose_name="correo")
    mensaje = models.TextField(verbose_name='mensaje', max_length=500)
    creado = models.DateTimeField(verbose_name='creado', auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str((self.creado))
    

core/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Contacto
from ordenes.models import Orden
class RegistroForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1","password2"]

class ContactoForm(ModelForm):
    class Meta:
        model = Contacto
        fields = [
            'nombre',
            'apellido',
            'correo',
            'mensaje'
        ]
        
        labels = {
            'nombre' : 'Nombre',
            'apellido' : 'Apellido',
            'correo' : 'Correo',
            'mensaje' : 'Mensaje'
        }
        
        widgets = {
            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
            'apellido' : forms.TextInput(attrs={'class':'form-control'}),
            'correo' : forms.TextInput(attrs={'class':'form-control'}),
            'mensaje' : forms.TextInput(attrs={'class':'form-control', 'id' : 'mensaje'}),
        }
    

core/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from guest_user.decorators import allow_guest_user
from django.db.models import Q
from .models import *
from gestionPedidos.models import Producto, Categoria
from ordenes.models import Orden, OrdenItem
from .forms import *
from carro.forms import anadirProductoForm
import bcrypt


def root(request):
    return redirect('/home')

@allow_guest_user
def home(request):
    context = {'productos': Producto.objects.all(), 'categoria' : Categoria.objects.all(), 'orden' : Orden.objects.all()}
    return render(request, "home.html", context)

def categoria(request, foo):
    foo = foo.replace('-', ' ')
    categoria = Categoria.objects.get(nombre=foo)
    print(categoria)
    productos = Producto.objects.filter(categoria=categoria)
    print(productos)
    return render(request, 'categoria.html', {'productos' : productos, 'categoria' : categoria })

def busca_ordenes(request):
    if request.method == 'POST':
        miorden = request.POST['miorden']
        try:
            orden = Orden.objects.get(id=miorden)
            items = OrdenItem.objects.filter(orden=miorden)
            print(miorden, orden, items)
            return render(request, 'buscaordenes.html', {'miorden' : miorden, 'orden':orden, 'items' : items})
        except:
            return redirect(reverse('busca-ordenes')+ '?NO_EXISTS')
    else:
        return render(request, 'buscaordenes.html')
    

def contacto(request):
    if request.method == 'POST':
        form = ContactoForm(request.POST)
        if form.is_valid():
            nombre = form.cleaned_data.get('nombre')
            apellido = form.cleaned_data.get('apellido')
            correo = form.cleaned_data.get('correo')
            mensaje = form.cleaned_data.get('mensaje')
            obj = Contacto.objects.create(
                nombre = nombre,
                apellido = apellido,
                correo = correo,
                mensaje = mensaje
            )
            obj.save()
            return redirect(reverse('home')+ '?OK')
        else:
            return redirect(reverse('contacto')+ '?FAIL')
    else:
        form = ContactoForm
    return render(request,'contacto.html',{'form':form})

def detalle_producto(request, id_producto):
    producto = get_object_or_404(Producto, id_producto=id_producto)
    form = anadirProductoForm()
    return render(request, 'productos/detalle_producto.html', {'producto': producto, 'form': form})
    
def registrar(request):
    data = {'form' : RegistroForm()}
    if request.method == 'POST':
        formulario = RegistroForm(data = request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(usermame = formulario.cleaned_data['username'], password = formulario.cleaned_data['password1'])
            if user is not None:
                login(request, user)
            messages.success(request, 'Usuario registrado satisfactoriamente.')
            return redirect('/')
        else:
            data['form'] = formulario
    return render(request, 'auth/registrar.html', data)
    
def exit(request):
    logout(request)
    return redirect('home')

core/templates/base.html
{% load static %}
{% load guest_user %}

<!DOCTYPE html>
<html lang="es-CL">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap v5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}" />

    <title>
      {% block title %}

      {% endblock %}- Solufood
    </title>
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar fixed-top">
      <a href="/">
        <div class="logo">
          <img src="{% static 'img/logo.svg' %}" alt="" />
        </div>
      </a>

      <div class="container-fluid">
        <div class="inicio">
          <a href="/">Inicio</a>
        </div>

        {% if user|is_guest_user %}
          <div class="carrito">
            <a href="{% url 'carro:detalle_carro' %}">
              <img src="{% static 'img/cart4.svg' %}" class="carrito-logo" />
              Carrito
            </a>
          </div>
          <div class="dropdown" id="menu">
            <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Categorías</button>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Hamburguesas' %}">Hamburguesas</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Pizzas' %}">Pizzas</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Sandwiches' %}">Sandwiches</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Papas' %}">Papas</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Acompañamientos' %}">Acompañamientos</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Refrescos' %}">Refrescos</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Helados' %}">Helados</a>
              </li>
            </ul>
          </div>
          <div class="login">
            <a class="nav-link active" aria-current="page" href="/login">Ingresar</a>
          </div>
          <div class="signup">
            <a class="nav-link active" aria-current="page" href="/registrar">Registrar</a>
          </div>
        {% else %}
          <div class="main-usuario">
            <b>Bienvenido, <span>{{ user.username }}</span></b>
          </div>
          <div class="dropdown" id="menu">
            <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Categorías</button>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Hamburguesas' %}">Hamburguesas</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Pizzas' %}">Pizzas</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Sandwiches' %}">Sandwiches</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Papas' %}">Papas</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Acompañamientos' %}">Acompañamientos</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Refrescos' %}">Refrescos</a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'categoria' 'Helados' %}">Helados</a>
              </li>
            </ul>
          </div>
          <div class="carrito">
            <a href="{% url 'carro:detalle_carro' %}">
              <img src="{% static 'img/cart4.svg' %}" class="carrito-logo" />
              Carrito
            </a>
          </div>
          {% if user.is_authenticated %}
            <div class="dropdown" id="menu">
              <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Cuenta</button>
              <ul class="dropdown-menu">
                <li></li>
                <li>
                  <a class="dropdown-item" href="{% url 'ordenes:ordenes' %}">Mis ordenes</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a>
                </li>
              </ul>
            </div>
          {% endif %}
        {% endif %}

        {% if user.is_staff %}
          <div class="dropdown" id="menu">
            <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Gestión</button>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="/ordenes/admin/ordenlist">Ver Órdenes</a>
              </li>
              <li>
                <a class="dropdown-item" href="/gestionPedidos/productos">Ver Productos</a>
              </li>
              <li>
                <a class="dropdown-item" href="/gestionPedidos/producto_nuevo">Agregar Productos</a>
              </li>
              <li>
                <a class="dropdown-item" href="/gestionPedidos/categoria_nuevo">Agregar Categoría</a>
              </li>
            </ul>
          </div>
        {% endif %}
        <div class="base-seguimiento">
          <a href="/ver-orden">Seguimiento</a>
        </div>
      </div>
    </nav>

    <!-- Contenedor Principal -->
    <main>
      {% block first_content %}

      {% endblock %}

      {% block second_content %}

      {% endblock %}

      {% block content %}

      {% endblock %}
    </main>

    <!-- Footer de pago -->
    <footer>
      <div class="footer-pago">
        <h4>Métodos de pago</h4>
        <img src="{% static 'img/american-express.svg' %}" />
        <img src="{% static 'img/mastercard.svg' %}" />
        <img src="{% static 'img/visa.svg' %}" />
      </div>

      <!-- Footer izquierdo -->
      <div class="footer-left">
        <ul>
          <li>
            <a href="{% url 'contacto' %}">Contacto</a>
            <a href="#">Nosotros</a>
            <a href="#">¿Buscas trabajo?</a>
          </li>
        </ul>
      </div>

      <!-- Footer de info -->
      <div class="footer-info">
        <p>Froilán Roa 7107</p>
        <p>La Florida</p>
        <p>Región Metropolitana</p>
        <p>(2) 2354 0700</p>
      </div>

      <!-- Footer de redes -->
      <div class="footer-redes">
        <a href="https://www.instagram.com/duoc_plazavespucio/"><img src="{% static 'img/instagram.svg' %}" /></a>
        <a href="https://www.facebook.com/DuocUC/"><img src="{% static 'img/facebook.svg' %}" /></a>
        <a href="https://x.com/duocuc"><img src="{% static 'img/twitter.svg' %}" /></a>
      </div>

      <!-- Footer de copy -->
      <div class="footer-divider">
        <hr class="solid" />
      </div>
      <div class="footer-copyright">
        <h6>Sitio web creado por estudiantes de la carrera Analista Programador 2024 Duoc UC</h6>
      </div>
    </footer>
  </body>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</html>

core/templates/buscaordenes.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  Ver tu orden
{% endblock %}

{% block first_content %}
  <div class="buscador-alerta">
    {% if 'NO_EXISTS' in request.GET %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Orden no encontrada.</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endif %}
  </div>
{% endblock %}

{% block second_content %}
  <div class="container-buscador">
    <form class="d-flex form-buscador" method="POST" action="{% url 'busca-ordenes' %}">
      {% csrf_token %}
      <h5>Revisa tu orden:</h5>
      <input type="search" class="form-control me-2" placeholder="N° de orden" name="miorden" />
      <button type="submit" class="btn buscar-button">Buscar</button>
    </form>

    {% if miorden %}
      {% load humanize %}
      <div class="card card-orden">
        <div class="card-body">
          <h5 class="card-title">Orden n° {{ orden.id }}</h5>
          <div class="detalle-orden">
            <ul>
              <li>
                <span>Nombre:</span> {{ orden.nombre }} {{ orden.apellido }}
              </li>
              <li>
                <span>Dirección:</span> {{ orden.direccion }}, {{ orden.comuna }}, {{ orden.ciudad }}
              </li>
              <li>
                <span>Teléfono:</span> {{ orden.telefono }}
              </li>
              <li>
                <span>Comentario:</span>
                {% if orden.comentario %}
                  {{ orden.comentario }}
                {% else %}
                  No hay comentario.
                {% endif %}
              </li>
              <li>
                <span>Productos:</span>
                <br />
                {% for i in items %}
                  {{ i.producto }} x {{ i.cantidad }} -- {{ i.precio|intcomma }}
                {% endfor %}
              </li>
            </ul>
          </div>

          <div class="footer-orden">
            {% if orden.cupon %}
              Subtotal: $ {{ orden.subtotal|intcomma }}
              <br />
              Descuento: $ {{ orden.descuento|intcomma }}
            {% endif %}
            <br />
            Total del pedido: $ {{ orden.total_oc|intcomma }}
            <br />
            Estado: <strong>{{ orden.estado }}</strong>
          </div>
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

core/templates/categoria.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ categoria }}{% endblock %}

{% block first_content%}{%endblock%}

{% block second_content%}
<section class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for p in productos %}
        <div class="col mx-auto">
          <div class="card container-items">
            <div class="card card-img-top item">
              {% if p.imagen %}
                <img class="img-afiche" src="{{ p.imagen.url }}" class="card-img-top p-2" alt="{{ p.nombre }}" />
              {% else %}
                <img src="{% static 'img/image_not_found.jpg' %}" class="card-img-top" alt="not found" />
              {% endif %}
              <div class="card-body producto-info">
                <p class="card-text text-muted">cod: {{ p.id_producto }}</p>
                <p href="">{{ p.nombre }}</p>
                <p class="card-text">{{ p.descripcion }}</p>
                {% load humanize %}
                <p class="card-text card-text-precio">Precio: ${{ p.precio|intcomma }}</p>
                <div class="agregar">
                  <a href="{{ p.get_absolute_url }}"><button class="boton-agregar">Ver</button></a>
                </div>
              </div>
              <div></div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </section>
</main>

{% endblock %}

core/templates/contacto.html
{% extends 'base.html' %}

{% block first_content %}

{% endblock %}

{% block title %}
  Contacto
{% endblock %}

{% block second_content %}
  <div class="card-contacto card text-bg-dark mb-3 opacity-75">
    <div class="card-body">
      <form id="formulario" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card-body">
          <div class="mb-3">
            <label for="nombre">Nombre:</label>
            <div class="input-group">{{ form.nombre }}</div>
          </div>

          <div class="mb-3">
            <label for="apellido">Apellido:</label>
            <div class="input-group">{{ form.apellido }}</div>
          </div>

          <div class="mb-3">
            <label for="correo">Correo eléctronico:</label>
            <div class="input-group">{{ form.correo }}</div>
          </div>

          <div class="mb-3">
            <label for="mensaje">Comentario:</label>
            <div class="input-group">{{ form.mensaje }}</div>
          </div>
        </div>
        <br />
        <div class="text-center my-4">
          <input type="submit" class="btn btn-primary m-2" id="registrar" value="Guardar" />
          <input type="reset" class="btn btn-danger m-2" id="limpiar" value="Limpiar" />
        </div>
        <hr />
      </form>
    </div>
  </div>
{% endblock %}

core/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  Inicio
{% endblock %}

<!-- Carousel -->
{% block first_content %}
  <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="2000">
        <img src="{% static 'img/banner1.png' %}" class="d-block w-100" />
      </div>
      <div class="carousel-item" data-bs-interval="2000">
        <img src="{% static 'img/banner2.png' %}" class="d-block w-100" />
      </div>
      <div class="carousel-item" data-bs-interval="2000">
        <img src="{% static 'img/banner3.png' %}" class="d-block w-100" />
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
{% endblock %}

<!-- Contenedor Principal -->
{% block second_content %}
  <main class="main-home">
    <h1>Menú</h1>
    <section class="container">
      <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for p in productos %}
          <div class="col mx-auto">
            <div class="card container-items">
              <div class="card card-img-top item">
                {% if p.imagen %}
                  <img class="img-afiche" src="{{ p.imagen.url }}" class="card-img-top p-2" alt="{{ p.nombre }}" />
                {% else %}
                  <img src="{% static 'img/image_not_found.jpg' %}" class="card-img-top" alt="not found" />
                {% endif %}
                <div class="card-body producto-info">
                  <p class="card-text text-muted">cod: {{ p.id_producto }}</p>
                  <p href="">{{ p.nombre }}</p>
                  <p class="card-text">{{ p.descripcion }}</p>
                  {% load humanize %}
                  <p class="card-text card-text-precio">Precio: ${{ p.precio|intcomma }}</p>
                  <div class="agregar">
                    <a href="{{ p.get_absolute_url }}"><button class="boton-agregar">Ver</button></a>
                  </div>
                </div>
                <div></div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </section>
  </main>
{% endblock %}